databases:
  - name: gesBackendApi
    plan: free
    databaseName: temp_restapi_db
    user: temp_restapi_db_user

services:
  - type: web
    plan: free
    name: gesBackendApi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn gesBackendApi.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: postgresql://temp_restapi_db_user:LqgAVqvUVWrqbHdPLqSVWR66SKOv57nj@dpg-cqqfi9bv2p9s73b6u38g-a/temp_restapi_db
        fromDatabase:
          name: temp_restapi_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4