# Generated by Django 4.2.14 on 2024-08-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0003_company_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
