# Generated by Django 4.2.14 on 2024-08-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0004_company_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
