# Generated by Django 4.2.14 on 2024-08-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0005_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
