# Generated by Django 4.2.14 on 2024-08-05 09:22

from django.db import migrations, models
import django.db.models.deletion
import productsCatalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantype',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fantypes', to='productsCatalogue.product'),
        ),
        migrations.AlterField(
            model_name='fantype',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='fan_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fantype', to='productsCatalogue.fantype'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=productsCatalogue.models.upload_to_product_image)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='productsCatalogue.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ManyToManyField(blank=True, related_name='products', to='productsCatalogue.productimage'),
        ),
    ]
