# Generated by Django 4.2.14 on 2024-08-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0007_fantype_product_alter_fantype_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
