# Generated by Django 4.2.14 on 2024-08-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0008_remove_product_img_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fan_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ManyToManyField(blank=True, related_name='products', to='productsCatalogue.productimage'),
        ),
    ]
