# Generated by Django 4.2.14 on 2024-08-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0011_product_color_product_material_product_warrenty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
