# Generated by Django 4.2.14 on 2024-08-09 10:24

from django.db import migrations, models
import django.db.models.deletion
import productsCatalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0012_delete_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.RemoveField(
            model_name='company',
            name='img',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productimages', to='productsCatalogue.product'),
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=productsCatalogue.models.upload_to_company_image)),
                ('company_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyprofileimg', to='productsCatalogue.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.ManyToManyField(blank=True, to='productsCatalogue.companyimage'),
        ),
    ]
