# Generated by Django 4.2.14 on 2024-08-12 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0013_alter_company_about_remove_company_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='img',
        ),
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productsCatalogue.companyimage'),
        ),
    ]
