# Generated by Django 4.2.14 on 2024-08-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0014_remove_company_img_company_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Airflow',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='RPM',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
