# Generated by Django 4.2.14 on 2024-08-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0016_remove_company_img_alter_companyimage_company_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='img',
        ),
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='productsCatalogue.companyimage'),
        ),
    ]
