# Generated by Django 4.2.14 on 2024-08-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsCatalogue', '0017_remove_company_img_company_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='img',
        ),
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.ManyToManyField(blank=True, related_name='companies', to='productsCatalogue.companyimage'),
        ),
    ]
